# version: 2.1
# orbs:
#   node: circleci/node@5
# jobs:
#   test-node:
#     # Install node dependencies and run tests
#     executor: node/default
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: npm
#       - run:
#           name: Run tests
#           command: npm test --passWithNoTests
#       - run:
#           name: Run ESLint
#           command: npm run lint # נוסיף פה הרצת eslint

#   deploy:
#     # This is an example deploy job, not actually used by the workflow
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
#       # Replace this with steps to deploy to users
#       - run:
#           name: Deploy to Production
#           command: '#e.g. ./deploy.sh'
#   build-test:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - run:
#           name: install dependencies
#           command: npm install
#       - run:
#           name: Run tests
#           command: npm test
#       - run:
#           name: Run ESLint
#           command: npm run lint # גם פה נוסיף הרצת eslint
# workflows:
#   build-and-test:
#     jobs:
#       - test-node
#       # Uncomment and configure deploy job when ready
#       # - deploy:
#       #     requires:
#       #       - test-node
#       - build-test
#       - deploy:
#         requires:
#           - build-test 






# version: 2.1

# orbs:
#   node: circleci/node@5

# jobs:
#   build-and-deploy:
#     executor: node/default
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: npm
#       - run:
#           name: Install dependencies
#           command: npm install
#       - run:
#           name: Run tests
#           command: npm test --passWithNoTests
#       - run:
#           name: Run linter
#           command: npm run lint
#       - run:
#           name: Deploy app to server
#           command: curl 'https://get-your-book-server.onrender.com'

# workflows:
#   version: 2
#   build-and-deploy:
#     jobs:
#       - build-and-deploy







version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-and-test-server:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test --passWithNoTests
      - run:
          name: Run linter
          command: npm run lint

  deploy-server:
    executor: node/default
    steps:
      - run:
          name: Deploy app to server
          command: curl 'https://exspresso-server.onrender.com'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test-server
      - deploy-server:
          requires:
            - build-and-test-server